import {Discovery,DiscoveryMotionDevice,DiscoveryMotionDeviceSystem,DiscoveryNode,DiscoveryPowerTrain,Snapshot,SnapshotValue} from '../api/types';

export type RuntimeMeasurement={owner:DiscoveryNode;path:string;value?:SnapshotValue;unit?:string|null;euRange?:string|null};
export type RuntimeAxis={system:DiscoveryMotionDeviceSystem;motionDevice:DiscoveryMotionDevice;axis:DiscoveryNode;position:RuntimeMeasurement;speed:RuntimeMeasurement;acceleration:RuntimeMeasurement};
export type RuntimeMotor={system:DiscoveryMotionDeviceSystem;motionDevice:DiscoveryMotionDevice;powerTrain:DiscoveryNode;motor:DiscoveryNode;temperature:RuntimeMeasurement};
const normalize=(text:string)=>text.replace(/[^a-z0-9]/gi,'').toLowerCase();
const snapshotValues=(snapshots:(Snapshot|undefined)[])=>snapshots.flatMap(snapshot=>snapshot?.sections.flatMap(section=>section.values)||[]);
const exact=(snapshots:(Snapshot|undefined)[],label:string)=>{const matches=snapshotValues(snapshots).filter(value=>normalize(value.label)===normalize(label));return matches.length===1?matches[0]:undefined;};
const measurement=(owner:DiscoveryNode,path:string,browseName:string,snapshots:(Snapshot|undefined)[]):RuntimeMeasurement=>{const value=exact(snapshots,`${path}.ParameterSet.${browseName}`);return {owner,path,value,unit:value?.engineeringUnits,euRange:value?.euRange};};
export const selectMotionDevices=(discovery?:Discovery)=>discovery?.motionDeviceSystems?.flatMap(system=>(system.motionDevices||[]).filter(motionDevice=>motionDevice?.node).map(motionDevice=>({system,motionDevice})))||[];
export const selectAxesForMotionDevice=(system:DiscoveryMotionDeviceSystem,motionDevice:DiscoveryMotionDevice,snapshots:(Snapshot|undefined)[]):RuntimeAxis[]=>(motionDevice.axes||[]).filter(axis=>axis?.browseName).map(axis=>{const path=`${motionDevice.node.browseName}.Axes.${axis.browseName}`;return {system,motionDevice,axis,position:measurement(axis,path,'ActualPosition',snapshots),speed:measurement(axis,path,'ActualSpeed',snapshots),acceleration:measurement(axis,path,'ActualAcceleration',snapshots)};});
export const selectPowerTrainsForMotionDevice=(motionDevice:DiscoveryMotionDevice):DiscoveryPowerTrain[]=>(motionDevice.powerTrains||[]).filter((powerTrain):powerTrain is DiscoveryPowerTrain=>Boolean(powerTrain?.node&&Array.isArray((powerTrain as DiscoveryPowerTrain).motors)));
export const selectMotorsForPowerTrain=(system:DiscoveryMotionDeviceSystem,motionDevice:DiscoveryMotionDevice,powerTrain:DiscoveryPowerTrain,snapshots:(Snapshot|undefined)[]):RuntimeMotor[]=>(powerTrain.motors||[]).filter(motor=>motor?.node?.browseName).map(motor=>{const path=`${motionDevice.node.browseName}.PowerTrains.${powerTrain.node.browseName}.Motors.${motor.node.browseName}`;return {system,motionDevice,powerTrain:powerTrain.node,motor:motor.node,temperature:measurement(motor.node,path,'MotorTemperature',snapshots)};});
