import {Discovery,Snapshot,SnapshotValue} from '../api/types';

export type SelectedRuntimeValue={value?:SnapshotValue;rule:string};
export type SelectedRuntimeValues={values:SnapshotValue[];rule:string};
const normalize=(value:string)=>value.replace(/[^a-z0-9]/gi,'').toLowerCase();
const values=(snapshots:(Snapshot|undefined)[])=>snapshots.flatMap(snapshot=>snapshot?.sections.flatMap(section=>section.values)||[]);
const exactLabel=(snapshots:(Snapshot|undefined)[],labels:string[],rule:string):SelectedRuntimeValue=>{const wanted=labels.map(normalize);const matches=values(snapshots).filter(entry=>wanted.includes(normalize(entry.label)));return {value:matches.length===1?matches[0]:undefined,rule:matches.length===1?rule:`${rule}; ${matches.length} exact matches`};};
const exactBrowseName=(snapshots:(Snapshot|undefined)[],browseNames:string[],rule:string):SelectedRuntimeValue=>{const wanted=browseNames.map(normalize);const matches=values(snapshots).filter(entry=>wanted.includes(normalize(entry.browseName)));return {value:matches.length===1?matches[0]:undefined,rule:matches.length===1?rule:`${rule}; ${matches.length} exact matches`};};
const allBrowseName=(snapshots:(Snapshot|undefined)[],browseName:string,rule:string):SelectedRuntimeValues=>({values:values(snapshots).filter(entry=>normalize(entry.browseName)===normalize(browseName)),rule});
const identityLabelCandidates=(discovery:Discovery|undefined,name:string)=>discovery?.motionDeviceSystems.flatMap(system=>system.motionDevices.map(device=>`${device.node.browseName}.${name}`))||[];
const selectedIdentity=(snapshots:(Snapshot|undefined)[],discovery:Discovery|undefined,name:string):SelectedRuntimeValue=>{const candidates=identityLabelCandidates(discovery,name);return candidates.length?exactLabel(snapshots,candidates,`exact discovered path: ${candidates.join(' / ')}`):exactBrowseName(snapshots,[name],`unique exact BrowseName: ${name}`);};
export const selectManufacturer=(discovery:Discovery|undefined,snapshot?:Snapshot,equipment?:Snapshot)=>selectedIdentity([equipment,snapshot],discovery,'Manufacturer');
export const selectModel=(discovery:Discovery|undefined,snapshot?:Snapshot,equipment?:Snapshot)=>selectedIdentity([equipment,snapshot],discovery,'Model');
export const selectSerialNumber=(discovery:Discovery|undefined,snapshot?:Snapshot,equipment?:Snapshot)=>selectedIdentity([equipment,snapshot],discovery,'SerialNumber');
const meaningful=(entry?:SnapshotValue)=>entry&&!/^\s*[-+]?\d+(\.\d+)?\s*$/.test(entry.valueText)&&entry.valueText!=='<not available>'?entry:undefined;
const stateText=(snapshot:Snapshot|undefined,path:string):SelectedRuntimeValue=>{const text=exactLabel([snapshot],[`${path}.CurrentState.ValueAsText`],`exact label: ${path}.CurrentState.ValueAsText`);if(meaningful(text.value))return text;const current=exactLabel([snapshot],[`${path}.CurrentState`],`fallback exact label: ${path}.CurrentState`);return {value:meaningful(current.value),rule:current.value?`${current.rule} (meaningful non-numeric text only)`:text.rule};};
export const selectSystemTopState=(s?:Snapshot)=>stateText(s,'SystemOperationStateMachine'); export const selectSystemIdleSubstate=(s?:Snapshot)=>stateText(s,'IdleSubstateMachine'); export const selectSystemExecutingSubstate=(s?:Snapshot)=>stateText(s,'ExecutingSubstateMachine'); export const selectTaskTopState=(s?:Snapshot)=>stateText(s,'TaskControlStateMachine'); export const selectTaskReadySubstate=(s?:Snapshot)=>stateText(s,'ReadySubstateMachine'); export const selectUnderControl=(s?:Snapshot)=>exactBrowseName([s],['UnderControl'],'exact BrowseName: UnderControl'); export const selectOperationalMode=(s?:Snapshot)=>exactBrowseName([s],['OperationalMode'],'exact BrowseName: OperationalMode'); export const selectProtectiveStop=(s?:Snapshot)=>exactBrowseName([s],['ProtectiveStop'],'exact BrowseName: ProtectiveStop'); export const selectEmergencyStop=(s?:Snapshot)=>exactBrowseName([s],['EmergencyStop'],'exact BrowseName: EmergencyStop'); export const selectProgramName=(s?:Snapshot)=>exactBrowseName([s],['TaskProgramName','CurrentProgramName'],'exact BrowseName: TaskProgramName/CurrentProgramName');
