import {useState} from 'react';
import {Discovery,Robot,Snapshot,LiveMessage,RobotDiagnostics,RobotStatus} from '../api/types';
import CommandPanel from './CommandPanel'; import RobotStructurePanel from './RobotStructurePanel'; import SnapshotPanel from './SnapshotPanel'; import LiveTimeline from './LiveTimeline'; import StateMachineView from './StateMachineView'; import StatusBadge from './StatusBadge'; import * as selectors from '../selectors/runtimeValueSelectors';
import RobotIdentity from './RobotIdentity'; import MotionDevicePanel from './MotionDevicePanel'; import Robot3DViewport from '../robot3d/Robot3DViewport';

type Props={robot:Robot;gateway:string;status?:RobotStatus;discovery?:Discovery;snapshot?:Snapshot;equipment?:Snapshot;diagnostics?:RobotDiagnostics;live:string;events:LiveMessage[];updates:Record<string,number>;error?:string;nextRetryAt?:number;reconnectAttempt:number;onRefresh:()=>void;onLive:()=>void};
const Lamp=({label,value}:{label:string;value:string})=><div className="fleet-lamp"><span className={`status-dot ${value}`}/><small>{label}</small><b>{value.toUpperCase()}</b></div>;
export default function RobotCard(p:Props){const [details,setDetails]=useState(false);const under=selectors.selectUnderControl(p.snapshot).value;const protective=selectors.selectProtectiveStop(p.snapshot).value;const emergency=selectors.selectEmergencyStop(p.snapshot).value;const mode=selectors.selectOperationalMode(p.snapshot).value;const program=selectors.selectProgramName(p.snapshot).value;const system=selectors.selectSystemTopState(p.snapshot).value;const task=selectors.selectTaskTopState(p.snapshot).value;const axes=p.discovery?.motionDeviceSystems?.flatMap(system=>system.motionDevices?.flatMap(device=>device.axes||[])||[])||[]; return <article className="robot-card card">
  <div className="robot-card-head"><div className="robot-identity-header"><Robot3DViewport axes={axes} snapshots={[p.snapshot,p.equipment]} live={p.live} imageUrl={p.robot.imageUrl}/><div className="robot-identity-copy"><span className="eyebrow">ROBOT / {p.robot.id}</span><h2>{p.robot.displayName}</h2><RobotIdentity discovery={p.discovery} snapshot={p.snapshot} equipment={p.equipment}/></div></div><div className="robot-card-actions"><button aria-label="Refresh robot" onClick={p.onRefresh}>↻</button><button className="live-button" onClick={p.onLive}><span className={`status-dot ${p.live}`}/>{p.live==='connected'?'Live':'Connect live'}</button></div></div>
  <div className="robot-health"><Lamp label="Gateway" value={p.status?.connected?'online':'offline'}/><Lamp label="OPC UA" value={p.status?.connected?'connected':'disconnected'}/><Lamp label="Live stream" value={p.live}/><span className="robot-endpoint">{p.robot.endpointUrl}</span></div>
  <div className="robot-kpis"><div className="kpi"><small>System operation</small><strong>{system?.valueText||'Unavailable'}</strong><StatusBadge value={system?.statusCode}/></div><div className="kpi"><small>Task control</small><strong>{task?.valueText||'Unavailable'}</strong><StatusBadge value={task?.statusCode}/></div><div className="kpi"><small>Control</small><strong>{under?.valueText||'Unavailable'}</strong><StatusBadge value={under?.statusCode}/></div><div className="kpi"><small>Mode</small><strong>{mode?.valueText||'Unavailable'}</strong><StatusBadge value={mode?.statusCode}/></div></div>
  <div className="indicator-row"><span className={protective?.valueText?.toLowerCase()==='true'?'indicator warning':'indicator'}>Protective stop <b>{protective?.valueText??'Unavailable'}</b></span><span className={emergency?.valueText?.toLowerCase()==='true'?'indicator danger':'indicator'}>Emergency stop <b>{emergency?.valueText??'Unavailable'}</b></span><span className="indicator">Program <b>{program?.valueText??'Unavailable'}</b></span></div>
  <MotionDevicePanel discovery={p.discovery} snapshot={p.snapshot} equipment={p.equipment}/>
  <div className="state-machines"><StateMachineView snapshot={p.snapshot} title="SystemOperation" kind="system"/><StateMachineView snapshot={p.snapshot} title="TaskControlOperation" kind="task"/></div>
  <CommandPanel base={p.gateway} robotId={p.robot.id} onDone={p.onRefresh}/>
  {p.error&&<div className="alert"><b>Robot issue</b><span>{p.error}</span></div>}
  <button className="details-toggle" aria-expanded={details} onClick={()=>setDetails(!details)}>{details?'⌃ Hide technical details':'⌄ Technical details'} <small>discovery · nodes · timestamps · live events</small></button>
  {details&&<div className="robot-details"><RobotStructurePanel data={p.discovery}/><SnapshotPanel snapshot={p.snapshot} updates={p.updates}/><SnapshotPanel snapshot={p.equipment} title="Equipment values" equipment updates={p.updates}/>{p.diagnostics&&<section className="card gateway-diagnostics"><div className="section-title">Gateway diagnostics<small>READ-ONLY QUALITY SUMMARY</small></div><div className="diagnostic-summary"><span>{p.diagnostics.connected?'Connected':'Disconnected'}</span><span>{p.diagnostics.sections.reduce((n,s)=>n+s.valueCount,0)} monitored snapshot values</span><span>{p.diagnostics.sections.reduce((n,s)=>n+s.nonGoodCount,0)} non-Good</span></div>{p.diagnostics.warnings.length>0&&<pre>{p.diagnostics.warnings.join('\n')}</pre>}</section>}<section className="card gateway-diagnostics"><div className="section-title">Live connection<small>PER-ROBOT RECOVERY</small></div><div className="diagnostic-summary"><span>{p.live}</span>{p.nextRetryAt&&<span>Next retry in {Math.max(0,Math.ceil((p.nextRetryAt-Date.now())/1000))}s</span>}{p.reconnectAttempt>0&&<span>Attempt {p.reconnectAttempt}</span>}</div></section><LiveTimeline items={p.events}/></div>}
</article>}
