import {useState} from 'react';
import {Discovery,Robot,Snapshot,LiveMessage,RobotDiagnostics,RobotStatus} from '../api/types';
import CommandPanel from './CommandPanel'; import RobotStructurePanel from './RobotStructurePanel'; import SnapshotPanel from './SnapshotPanel'; import LiveTimeline from './LiveTimeline'; import StateMachineView from './StateMachineView'; import * as selectors from '../selectors/runtimeValueSelectors';
import MotionDevicePanel from './MotionDevicePanel'; import RobotOverview from './RobotOverview';

type Props={robot:Robot;gateway:string;status?:RobotStatus;discovery?:Discovery;snapshot?:Snapshot;equipment?:Snapshot;diagnostics?:RobotDiagnostics;live:string;events:LiveMessage[];updates:Record<string,number>;error?:string;nextRetryAt?:number;reconnectAttempt:number;onRefresh:()=>void;onLive:()=>void};
const Lamp=({label,value}:{label:string;value:string})=><div className="fleet-lamp"><span className={`status-dot ${value}`}/><small>{label}</small><b>{value.toUpperCase()}</b></div>;
export default function RobotCard(p:Props){const [details,setDetails]=useState(false);const underSelection=selectors.selectUnderControl(p.snapshot);const protective=selectors.selectProtectiveStop(p.snapshot).value;const emergency=selectors.selectEmergencyStop(p.snapshot).value;const program=selectors.selectProgramName(p.snapshot).value;const modeSelection=selectors.selectOperationalMode(p.snapshot);const systemSelection=selectors.selectSystemTopState(p.snapshot);const taskSelection=selectors.selectTaskTopState(p.snapshot);const axes=p.discovery?.motionDeviceSystems?.flatMap(system=>system.motionDevices?.flatMap(device=>device.axes||[])||[])||[]; return <article className="robot-card card">
  <RobotOverview robot={p.robot} discovery={p.discovery} snapshot={p.snapshot} equipment={p.equipment} axes={axes} live={p.live} states={{system:systemSelection,task:taskSelection,control:underSelection,mode:modeSelection}} onRefresh={p.onRefresh} onLive={p.onLive}/>
  <div className="robot-health"><Lamp label="Gateway" value={p.status?.connected?'online':'offline'}/><Lamp label="OPC UA" value={p.status?.connected?'connected':'disconnected'}/><Lamp label="Live stream" value={p.live}/><span className="robot-endpoint">{p.robot.endpointUrl}</span></div>
  <div className="indicator-row"><span className={protective?.valueText?.toLowerCase()==='true'?'indicator warning':'indicator'}>Protective stop <b>{protective?.valueText??'Unavailable'}</b></span><span className={emergency?.valueText?.toLowerCase()==='true'?'indicator danger':'indicator'}>Emergency stop <b>{emergency?.valueText??'Unavailable'}</b></span><span className="indicator">Program <b>{program?.valueText??'Unavailable'}</b></span></div>
  <MotionDevicePanel discovery={p.discovery} snapshot={p.snapshot} equipment={p.equipment}/>
  <div className="state-machines"><StateMachineView snapshot={p.snapshot} title="SystemOperation" kind="system"/><StateMachineView snapshot={p.snapshot} title="TaskControlOperation" kind="task"/></div>
  <CommandPanel base={p.gateway} robotId={p.robot.id} onDone={p.onRefresh}/>
  {p.error&&<div className="alert"><b>Robot issue</b><span>{p.error}</span></div>}
  <button className="details-toggle" aria-expanded={details} onClick={()=>setDetails(!details)}>{details?'⌃ Hide technical details':'⌄ Technical details'} <small>discovery · nodes · timestamps · live events</small></button>
  {details&&<div className="robot-details"><RobotStructurePanel data={p.discovery}/><SnapshotPanel snapshot={p.snapshot} updates={p.updates}/><SnapshotPanel snapshot={p.equipment} title="Equipment values" equipment updates={p.updates}/>{p.diagnostics&&<section className="card gateway-diagnostics"><div className="section-title">Gateway diagnostics<small>READ-ONLY QUALITY SUMMARY</small></div><div className="diagnostic-summary"><span>{p.diagnostics.connected?'Connected':'Disconnected'}</span><span>{p.diagnostics.sections.reduce((n,s)=>n+s.valueCount,0)} monitored snapshot values</span><span>{p.diagnostics.sections.reduce((n,s)=>n+s.nonGoodCount,0)} non-Good</span></div>{p.diagnostics.warnings.length>0&&<pre>{p.diagnostics.warnings.join('\n')}</pre>}</section>}<section className="card gateway-diagnostics"><div className="section-title">Live connection<small>PER-ROBOT RECOVERY</small></div><div className="diagnostic-summary"><span>{p.live}</span>{p.nextRetryAt&&<span>Next retry in {Math.max(0,Math.ceil((p.nextRetryAt-Date.now())/1000))}s</span>}{p.reconnectAttempt>0&&<span>Attempt {p.reconnectAttempt}</span>}</div></section><LiveTimeline items={p.events}/></div>}
</article>}
