import {useCallback,useEffect,useRef,useState} from 'react';
import * as api from './api/gatewayClient'; import {Discovery,Snapshot,LiveMessage} from './api/types';
import ConnectionPanel from './components/ConnectionPanel'; import RobotStructurePanel from './components/RobotStructurePanel'; import SnapshotPanel from './components/SnapshotPanel'; import CommandPanel from './components/CommandPanel'; import LiveTimeline from './components/LiveTimeline';
export default function App(){
 const [gateway,setGateway]=useState(api.DEFAULT_GATEWAY),[health,setHealth]=useState('offline'),[opcua,setOpcua]=useState('disconnected'),[discovery,setDiscovery]=useState<Discovery>(),[snapshot,setSnapshot]=useState<Snapshot>(),[equipment,setEquipment]=useState<Snapshot>(),[live,setLive]=useState('disconnected'),[events,setEvents]=useState<LiveMessage[]>([]),[updates,setUpdates]=useState<Record<string,number>>({}),[diag,setDiag]=useState({count:0,lastAt:'',lastLabel:''}),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[lastRefresh,setLastRefresh]=useState<Date>(), [showcase,setShowcase]=useState(false); const ws=useRef<WebSocket | null>(null);
 const refresh=useCallback(async()=>{setHealth('checking');setError('');try{await api.getHealth(gateway);setHealth('online');const[o,d,s,e]=await Promise.all([api.getOpcUaStatus(gateway),api.getDiscovery(gateway),api.getSnapshot(gateway,'all'),api.getSnapshot(gateway,'equipment')]);setOpcua(o.connected?'connected':'disconnected');setDiscovery(d);setSnapshot(s);setEquipment(e);setLastRefresh(new Date());if(!o.connected)setError('OPC UA server disconnected')}catch(e){setHealth('offline');setOpcua('disconnected');setError(e instanceof TypeError?'Gateway unreachable or CORS/network issue':e instanceof Error?e.message:'Gateway unreachable')}} ,[gateway]);
 const onLive=useCallback((m:LiveMessage)=>{setEvents(x=>[m,...x].slice(0,200));if(!m.nodeId)return;const now=Date.now(),merge=(s?:Snapshot)=>s&&({...s,sections:s.sections.map(sec=>({...sec,values:sec.values.map(v=>v.nodeId===m.nodeId?({...v,valueText:m.valueText??v.valueText,statusCode:m.statusCode??v.statusCode,sourceTimestamp:m.sourceTimestamp??v.sourceTimestamp,serverTimestamp:m.serverTimestamp??v.serverTimestamp}):v)}))});setSnapshot(merge);setEquipment(merge);setUpdates(x=>({...x,[m.nodeId]:now}));setDiag(x=>({count:x.count+1,lastAt:m.timestampUtc||m.generatedAtUtc||new Date(now).toISOString(),lastLabel:m.label||m.nodeId}))},[]);
 const connect=()=>{try{ws.current?.close();ws.current=api.createLiveWebSocket(gateway,onLive,setLive)}catch{setLive('error')}}; const toggle=()=>ws.current?.readyState===WebSocket.OPEN?ws.current.close():connect(); useEffect(()=>{refresh();connect();return()=>ws.current?.close()},[refresh]);
 return <div className={showcase?'app showcase':'app'}><header><div><span className="eyebrow">REFERENCE IMPLEMENTATION · C13</span><h1>OPC UA Robotics <i>Workbench</i></h1><p>Premium cockpit for standards-led connected motion systems</p></div><div className="header-right"><div className="header-mark">◈<span>ROBOTICS<br/>MODEL</span></div><button className="showcase-toggle" onClick={()=>setShowcase(!showcase)}>▣ {showcase?'Exit tradeshow':'Tradeshow mode'}</button></div></header><ConnectionPanel gateway={gateway} setGateway={setGateway} health={health} opcua={opcua} live={live} error={error} lastRefresh={lastRefresh} onRefresh={refresh} onLive={toggle}/><div className="live-diagnostics card"><span className={`status-dot ${live}`}/><b>Live diagnostics</b><span>{diag.count} notifications</span><span>{diag.lastAt?`Last ${new Date(diag.lastAt).toLocaleTimeString()}`:'Waiting for dataChange'}</span><span>{diag.lastLabel}</span></div><nav className="section-tabs">{[['overview','Overview'],['commands','Commands'],['live','Live'],['structure','Structure'],['technical','Technical']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav><main><div className="panel-structure" data-section="structure"><RobotStructurePanel data={discovery}/></div><div className="panel-state" data-section="overview"><SnapshotPanel snapshot={snapshot} updates={updates}/></div><div className="panel-commands" data-section="commands"><CommandPanel base={gateway} onDone={refresh}/></div><div className="panel-equipment" data-section="overview"><SnapshotPanel snapshot={equipment} title="Equipment values" equipment updates={updates}/></div><div className="panel-live" data-section="live"><LiveTimeline items={events}/></div></main><footer>Reference implementation · Values and evidence are reported by the gateway · OPC UA semantics remain server-owned</footer></div>}
