import {useCallback,useEffect,useRef,useState} from 'react';
import * as api from './api/gatewayClient'; import {Discovery,LiveMessage,Robot,RobotDiagnostics,RobotStatus,Snapshot} from './api/types'; import RobotCard from './components/RobotCard';
type RobotViewState={status?:RobotStatus;discovery?:Discovery;snapshot?:Snapshot;equipment?:Snapshot;diagnostics?:RobotDiagnostics;live:string;events:LiveMessage[];updates:Record<string,number>;error?:string};
const blank=():RobotViewState=>({live:'disconnected',events:[],updates:{}});
const seedGoodValues=(snapshot?:Snapshot)=>snapshot&&({...snapshot,sections:snapshot.sections.map(section=>({...section,values:section.values.map(value=>/^Good/i.test(value.statusCode||'')?({...value,lastGoodValueText:value.valueText,lastGoodSourceTimestamp:value.sourceTimestamp,lastGoodServerTimestamp:value.serverTimestamp,lastGoodUpdatedAt:Date.now()}):value)}))});
export default function App(){
 const [gateway,setGateway]=useState(api.DEFAULT_GATEWAY),[robots,setRobots]=useState<Robot[]>([]),[views,setViews]=useState<Record<string,RobotViewState>>({}),[health,setHealth]=useState('checking'),[error,setError]=useState(''),[lastRefresh,setLastRefresh]=useState<Date>(),[showcase,setShowcase]=useState(false); const sockets=useRef<Record<string,WebSocket>>({});
 const update=useCallback((id:string,fn:(v:RobotViewState)=>RobotViewState)=>setViews(x=>({...x,[id]:fn(x[id]||blank())})),[]);
 const loadRobot=useCallback(async(robot:Robot)=>{update(robot.id,v=>({...v,error:undefined}));try{const [status,discovery,snapshot,equipment,diagnostics]=await Promise.all([api.getRobotStatus(gateway,robot.id).catch(e=>({robotId:robot.id,displayName:robot.displayName,endpointUrl:robot.endpointUrl,connected:false,roboticsNamespaceFound:false,error:e instanceof Error?e.message:String(e)})),api.getRobotDiscovery(gateway,robot.id),api.getRobotSnapshot(gateway,robot.id,'states'),api.getRobotSnapshot(gateway,robot.id,'equipment'),api.getRobotDiagnostics(gateway,robot.id).catch(()=>undefined)]);update(robot.id,v=>({...v,status,discovery,snapshot:seedGoodValues(snapshot),equipment:seedGoodValues(equipment),diagnostics,error:status.connected?'':status.error||undefined}));}catch(e){update(robot.id,v=>({...v,error:e instanceof Error?e.message:String(e),status:{...v.status,connected:false,robotId:robot.id,displayName:robot.displayName,endpointUrl:robot.endpointUrl,roboticsNamespaceFound:false}}));}},[gateway]);
 const connectRobot=useCallback((robot:Robot)=>{sockets.current[robot.id]?.close();const ws=api.createRobotLiveSocket(gateway,robot.id,{selection:'all',sendInitialSnapshot:true});sockets.current[robot.id]=ws;update(robot.id,v=>({...v,live:'connecting'}));ws.onopen=()=>update(robot.id,v=>({...v,live:'connected'}));ws.onclose=()=>update(robot.id,v=>({...v,live:'disconnected'}));ws.onerror=()=>update(robot.id,v=>({...v,live:'error'}));ws.onmessage=e=>{try{const m:LiveMessage=JSON.parse(e.data);update(robot.id,v=>{const merge=(s?:Snapshot)=>s&&({...s,sections:s.sections.map(sec=>({...sec,values:sec.values.map(x=>{if(x.nodeId!==m.nodeId)return x;const good=/^Good/i.test(m.statusCode||'');return {...x,valueText:good?(m.valueText??x.valueText):(x.lastGoodValueText??x.valueText),statusCode:m.statusCode??x.statusCode,sourceTimestamp:m.sourceTimestamp??x.sourceTimestamp,serverTimestamp:m.serverTimestamp??x.serverTimestamp,...(good?{lastGoodValueText:m.valueText??x.valueText,lastGoodSourceTimestamp:m.sourceTimestamp??x.sourceTimestamp,lastGoodServerTimestamp:m.serverTimestamp??x.serverTimestamp,lastGoodUpdatedAt:Date.now()}:{})};})}))});return {...v,events:[m,...v.events].slice(0,40),snapshot:merge(v.snapshot),equipment:merge(v.equipment),updates:m.nodeId?{...v.updates,[m.nodeId]:Date.now()}:v.updates};});}catch{}};},[gateway,update]);
 const refresh=useCallback(async()=>{setHealth('checking');setError('');try{const list=await api.getRobots(gateway);setRobots(list);setViews(old=>Object.fromEntries(list.map(r=>[r.id,old[r.id]||blank()])));await Promise.all(list.map(loadRobot));setHealth('online');setLastRefresh(new Date());}catch(e){setHealth('offline');setError(e instanceof Error?e.message:'Gateway unreachable');}},[gateway,loadRobot]);
 useEffect(()=>{refresh();return()=>Object.values(sockets.current).forEach(x=>x.close())},[refresh]);
 useEffect(()=>{robots.forEach(r=>{if(!sockets.current[r.id]||sockets.current[r.id].readyState===WebSocket.CLOSED)connectRobot(r)});},[robots,connectRobot]);
 return <div className={showcase?'app showcase':'app'}><header><div><span className="eyebrow">REFERENCE IMPLEMENTATION · C17</span><h1>OPC UA Robotics <i>Fleet</i></h1><p>A calm, standards-led view of connected motion systems</p></div><div className="header-right"><div className="header-mark">◈<span>ROBOTICS<br/>MODEL</span></div><button className="showcase-toggle" onClick={()=>setShowcase(!showcase)}>▣ {showcase?'Exit tradeshow':'Tradeshow mode'}</button></div></header><section className="fleet-toolbar card"><div><span className={`status-dot ${health}`}/><b>Gateway {health}</b><span className="fleet-count">{robots.length} configured robot{robots.length===1?'':'s'}</span>{lastRefresh&&<small>Updated {lastRefresh.toLocaleTimeString()}</small>}</div><div className="url-row"><input aria-label="Gateway URL" value={gateway} onChange={e=>setGateway(e.target.value)}/><button onClick={refresh}>↻ Refresh fleet</button></div></section>{error&&<div className="fleet-error alert"><b>Gateway issue</b><span>{error}</span></div>}<main className="fleet-grid">{robots.length?robots.map(robot=><RobotCard key={robot.id} robot={robot} gateway={gateway} {...(views[robot.id]||blank())} onRefresh={()=>loadRobot(robot)} onLive={()=>connectRobot(robot)}/>):<div className="card empty"><b>No enabled robots configured</b><span>The gateway registry returned no enabled robots.</span></div>}</main><footer>Reference implementation · values and evidence are reported by the gateway · OPC UA semantics remain server-owned</footer></div>}
