import { RobotVisualAssembly } from './assembly';
import { DiscoveryNode } from '../api/types';
import { ResolvedVisualJoint } from './types';
import { deepFreeze, identityTransform, RobotVisualTopology } from './topology';
import { compileVisualTopology } from './topologyValidator';

const axis = (device: string, name: string): DiscoveryNode => ({ browseName: name, displayName: name, nodeId: `synthetic/${device}/${name}`, stableKey: `${device}/${name}`, typeDefinition: 'AxisType', evidence: 'synthetic fixture', namespaceUri: 'urn:workbench:synthetic' });
const revolute = (jointId: string, parentNodeId: string, childNodeId: string, visualJointId: string) => ({ jointId, jointType: 'revolute' as const, parentNodeId, childNodeId, localTransform: identityTransform(), axis: { x: 0, y: 1, z: 0 }, resolvedVisualJointId: visualJointId });
const fixed = (jointId: string, parentNodeId: string, childNodeId: string) => ({ jointId, jointType: 'fixed' as const, parentNodeId, childNodeId, localTransform: identityTransform() });
const topology = (topologyId: string, roots: string[], nodes: RobotVisualTopology['nodes'], joints: RobotVisualTopology['joints']): RobotVisualTopology => deepFreeze({ topologyId, version: 'C18C.2c', displayName: topologyId, rootNodeIds: roots, singleRoot: false, nodes, joints, geometries: [] });
const resolved = (visualJointId: string, device: string, statusCode = 'Good', diagnosticState: ResolvedVisualJoint['diagnosticState'] = 'bound'): ResolvedVisualJoint => ({ visualJointId, profileId: 'synthetic-workbench-fixture', sourceMotionDeviceKey: device, sourceAxisKey: `${device}/${visualJointId}`, sourceAxis: axis(device, visualJointId), requiredUnitCategory: 'angular', conversion: { unit: 'radians', scale: 1 }, rawValue: 0, convertedVisualValue: 0, freshness: diagnosticState === 'bound' ? 'live' : 'unavailable', diagnosticState, statusCode });
const chain = (chainId: string, rootNodeId: string, visualJointIds: string[], device: string, fallbackPolicy: 'static' | 'neutral' | 'omit' = 'neutral') => ({ chainId, displayName: chainId, rootNodeId, requiredBindings: visualJointIds.map(visualJointId => ({ visualJointId, motionDeviceKey: device, required: true })), requiredVisualJointIds: visualJointIds, fallbackPolicy });

export type SyntheticAssemblyFixture = Readonly<{ assembly: RobotVisualAssembly; topology: ReturnType<typeof compileVisualTopology>; joints: readonly ResolvedVisualJoint[] }>;

export const railMountedSixAxisArmFixture: SyntheticAssemblyFixture = (() => {
  const armNodes = ['arm-root', 'arm-link1', 'arm-link2', 'arm-link3', 'arm-link4', 'arm-link5', 'arm-link6'].map((nodeId, index) => ({ nodeId, parentJointId: index ? `arm-j${index}` : undefined, localTransform: identityTransform() }));
  const railTopology = topology('synthetic-rail-mounted-arm', ['rail-root', 'arm-root'], [{ nodeId: 'rail-root', localTransform: identityTransform() }, { nodeId: 'carriage', parentJointId: 'rail', localTransform: identityTransform() }, ...armNodes], [{ jointId: 'rail', jointType: 'prismatic', parentNodeId: 'rail-root', childNodeId: 'carriage', localTransform: identityTransform(), axis: { x: 1, y: 0, z: 0 }, resolvedVisualJointId: 'rail', scale: 1 }, ...armNodes.slice(1).map((node, index) => revolute(`arm-j${index + 1}`, armNodes[index].nodeId, node.nodeId, `arm-${index + 1}`))]);
  return { assembly: { assemblyId: 'synthetic-rail-mounted-arm', displayName: 'Synthetic rail-mounted arm', topologyId: railTopology.topologyId, roots: [{ rootId: 'rail-root', rootNodeId: 'rail-root', localTransform: identityTransform() }], chains: [chain('rail-chain', 'rail-root', ['rail'], 'rail-device'), chain('arm-chain', 'arm-root', ['arm-1', 'arm-2', 'arm-3', 'arm-4', 'arm-5', 'arm-6'], 'arm-device')], attachments: [{ attachmentId: 'rail-carriage-to-arm', parentChainId: 'rail-chain', parentNodeId: 'carriage', childChainId: 'arm-chain', childRootNodeId: 'arm-root', localTransform: identityTransform() }], sharedFixedNodeIds: [] }, topology: compileVisualTopology(railTopology), joints: [resolved('rail', 'rail-device'), ...['arm-1', 'arm-2', 'arm-3', 'arm-4', 'arm-5', 'arm-6'].map(id => resolved(id, 'arm-device'))] };
})();

export const robotPlusIndependentPositionerFixture: SyntheticAssemblyFixture = (() => {
  const t = topology('synthetic-arm-positioner', ['arm-root', 'positioner-root'], [{ nodeId: 'arm-root', localTransform: identityTransform() }, { nodeId: 'arm-link', parentJointId: 'arm-j', localTransform: identityTransform() }, { nodeId: 'positioner-root', localTransform: identityTransform() }, { nodeId: 'positioner', parentJointId: 'positioner-j', localTransform: identityTransform() }], [revolute('arm-j', 'arm-root', 'arm-link', 'arm-1'), revolute('positioner-j', 'positioner-root', 'positioner', 'positioner-1')]);
  return { assembly: { assemblyId: 'synthetic-arm-positioner', displayName: 'Synthetic arm and independent positioner', topologyId: t.topologyId, roots: [{ rootId: 'arm', rootNodeId: 'arm-root', localTransform: identityTransform() }, { rootId: 'positioner', rootNodeId: 'positioner-root', localTransform: identityTransform() }], chains: [chain('arm-chain', 'arm-root', ['arm-1'], 'arm-device'), chain('positioner-chain', 'positioner-root', ['positioner-1'], 'positioner-device', 'omit')], sharedFixedNodeIds: [] }, topology: compileVisualTopology(t), joints: [resolved('arm-1', 'arm-device'), resolved('positioner-1', 'positioner-device')] };
})();

export const dualArmSharedBaseFixture: SyntheticAssemblyFixture = (() => {
  const t = topology('synthetic-dual-arm', ['shared-base'], [{ nodeId: 'shared-base', localTransform: identityTransform() }, { nodeId: 'left-root', parentJointId: 'left-mount', localTransform: identityTransform() }, { nodeId: 'right-root', parentJointId: 'right-mount', localTransform: identityTransform() }, { nodeId: 'left-tip', parentJointId: 'left-j', localTransform: identityTransform() }, { nodeId: 'right-tip', parentJointId: 'right-j', localTransform: identityTransform() }], [fixed('left-mount', 'shared-base', 'left-root'), fixed('right-mount', 'shared-base', 'right-root'), revolute('left-j', 'left-root', 'left-tip', 'left-1'), revolute('right-j', 'right-root', 'right-tip', 'right-1')]);
  return { assembly: { assemblyId: 'synthetic-dual-arm', displayName: 'Synthetic dual arm shared base', topologyId: t.topologyId, roots: [{ rootId: 'shared-base', rootNodeId: 'shared-base', localTransform: identityTransform() }], chains: [chain('left-arm', 'left-root', ['left-1'], 'left-device'), chain('right-arm', 'right-root', ['right-1'], 'right-device')], sharedFixedNodeIds: ['shared-base'] }, topology: compileVisualTopology(t), joints: [resolved('left-1', 'left-device'), resolved('right-1', 'right-device')] };
})();
