import { describe, expect, it } from 'vitest';
import { referenceServerSixAxisTopology } from './referenceServerSixAxisTopology';
import { resolveJointMotion, RobotVisualTopology } from './topology';
import { compileVisualTopology, validateVisualTopology } from './topologyValidator';

const vector = (x = 0, y = 0, z = 0) => ({ x, y, z });
const transform = () => ({ translation: vector(), rotation: { x: 0, y: 0, z: 0, order: 'XYZ' as const } });
const valid = (): RobotVisualTopology => ({ topologyId: 'fixture', version: '1', displayName: 'Fixture', rootNodeIds: ['root'], singleRoot: true, nodes: [{ nodeId: 'root', localTransform: transform() }, { nodeId: 'child', parentJointId: 'j', localTransform: transform() }], joints: [{ jointId: 'j', jointType: 'revolute', parentNodeId: 'root', childNodeId: 'child', localTransform: transform(), axis: vector(0, 0, 2), resolvedVisualJointId: 'joint', direction: -1, scale: 2, zeroOffset: 0.5 }], geometries: [] });
const error = (topology: RobotVisualTopology, code: string) => validateVisualTopology(topology).diagnostics.some(item => item.code === code && item.severity === 'error');
const withChanges = (changes: Partial<RobotVisualTopology>) => ({ ...valid(), ...changes });

describe('generic visual topology validation and compilation', () => {
  it('validates the current single-root six-axis topology and compiles deterministic traversal', () => { const result = validateVisualTopology(referenceServerSixAxisTopology); expect(result.valid).toBe(true); const reversed = { ...referenceServerSixAxisTopology, nodes: [...referenceServerSixAxisTopology.nodes].reverse(), joints: [...referenceServerSixAxisTopology.joints].reverse() }; const a = compileVisualTopology(referenceServerSixAxisTopology); const b = compileVisualTopology(reversed); expect(a.traversal.rootNodeIds).toEqual(b.traversal.rootNodeIds); expect(a.traversal.childJointIdsByNodeId.get('link1')).toEqual(['joint-shoulder']); const branch: RobotVisualTopology = { topologyId: 'branch', version: '1', displayName: 'Branch', rootNodeIds: ['root'], singleRoot: true, nodes: [{ nodeId: 'root', localTransform: transform() }, { nodeId: 'a', parentJointId: 'ja', localTransform: transform() }, { nodeId: 'b', parentJointId: 'jb', localTransform: transform() }], joints: [{ jointId: 'jb', jointType: 'fixed', parentNodeId: 'root', childNodeId: 'b', localTransform: transform() }, { jointId: 'ja', jointType: 'fixed', parentNodeId: 'root', childNodeId: 'a', localTransform: transform() }] }; expect(compileVisualTopology(branch).traversal.childJointIdsByNodeId.get('root')).toEqual(['ja', 'jb']); });
  it('supports fixed, revolute, and prismatic joints', () => { const fixed = withChanges({ nodes: [{ nodeId: 'root', localTransform: transform() }, { nodeId: 'child', parentJointId: 'fixed', localTransform: transform() }], joints: [{ jointId: 'fixed', jointType: 'fixed', parentNodeId: 'root', childNodeId: 'child', localTransform: transform() }] }); expect(validateVisualTopology(fixed).valid).toBe(true); expect(resolveJointMotion(fixed.joints[0], 20).rotationRadians).toBe(0); expect(resolveJointMotion(valid().joints[0], 1).rotationRadians).toBe(-1.5); const prismatic = withChanges({ joints: [{ ...valid().joints[0], jointType: 'prismatic', axis: vector(0, 2, 0), zeroOffset: 0, direction: 1, scale: 3 }] }); expect(resolveJointMotion(prismatic.joints[0], 2).translation).toEqual({ x: 0, y: 6, z: 0 }); });
  it('rejects duplicate IDs, missing roots, unknown references, and multiple parents', () => { expect(error(withChanges({ nodes: [...valid().nodes, valid().nodes[1]] }), 'duplicate-node-id')).toBe(true); expect(error(withChanges({ rootNodeIds: ['missing'] }), 'missing-root-node')).toBe(true); expect(error(withChanges({ joints: [{ ...valid().joints[0], parentNodeId: 'missing' }] }), 'unknown-parent-node')).toBe(true); expect(error(withChanges({ joints: [valid().joints[0], { ...valid().joints[0], jointId: 'j2', childNodeId: 'child' }] }), 'multiple-parent-joints')).toBe(true); });
  it('rejects direct and indirect cycles, disconnected nodes, and orphan joints', () => { const direct = withChanges({ joints: [valid().joints[0], { jointId: 'back', jointType: 'fixed', parentNodeId: 'child', childNodeId: 'root', localTransform: transform() }] }); expect(error(direct, 'cycle')).toBe(true); const indirect = withChanges({ nodes: [...valid().nodes, { nodeId: 'leaf', parentJointId: 'j2', localTransform: transform() }], joints: [{ ...valid().joints[0], childNodeId: 'child' }, { jointId: 'j2', jointType: 'fixed', parentNodeId: 'child', childNodeId: 'leaf', localTransform: transform() }, { jointId: 'j3', jointType: 'fixed', parentNodeId: 'leaf', childNodeId: 'child', localTransform: transform() }] }); expect(error(indirect, 'cycle')).toBe(true); expect(error(withChanges({ nodes: [...valid().nodes, { nodeId: 'orphan', localTransform: transform() }] }), 'disconnected-node')).toBe(true); expect(error(withChanges({ joints: [...valid().joints, { jointId: 'orphan-joint', jointType: 'fixed', parentNodeId: 'missing', childNodeId: 'missing', localTransform: transform() }] }), 'orphan-joint')).toBe(true); });
  it('enforces dynamic binding, axis, calibration, limits, geometry, and fixed-joint rules', () => { expect(error(withChanges({ joints: [{ ...valid().joints[0], resolvedVisualJointId: undefined }] }), 'missing-required-binding')).toBe(true); expect(error(withChanges({ joints: [{ ...valid().joints[0], axis: vector() }] }), 'invalid-joint-axis')).toBe(true); expect(error(withChanges({ joints: [{ ...valid().joints[0], scale: 0 }] }), 'zero-joint-scale')).toBe(true); expect(error(withChanges({ joints: [{ ...valid().joints[0], limit: { lower: 2, upper: 1 } }] }), 'invalid-joint-limits')).toBe(true); expect(error(withChanges({ joints: [{ ...valid().joints[0], resolvedVisualJointId: 'same' }, { ...valid().joints[0], jointId: 'j2', resolvedVisualJointId: 'same' }] }), 'duplicate-visual-joint-binding')).toBe(true); expect(error(withChanges({ nodes: [{ nodeId: 'root', localTransform: transform(), geometryIds: ['missing'] }, valid().nodes[1]] }), 'missing-geometry-definition')).toBe(true); const fixed = withChanges({ joints: [{ jointId: 'fixed', jointType: 'fixed', parentNodeId: 'root', childNodeId: 'child', localTransform: transform(), resolvedVisualJointId: 'bad' }] }); expect(error(fixed, 'fixed-joint-binding')).toBe(true); });
  it('rejects non-finite transforms and reports optional unbound joints as warnings', () => { expect(error(withChanges({ nodes: [{ nodeId: 'root', localTransform: { translation: { x: Number.NaN, y: 0, z: 0 }, rotation: { x: 0, y: 0, z: 0 } } }, valid().nodes[1]] }), 'non-finite-transform')).toBe(true); const optional = withChanges({ joints: [{ ...valid().joints[0], resolvedVisualJointId: undefined, bindingRequired: false }] }); expect(validateVisualTopology(optional).valid).toBe(true); expect(validateVisualTopology(optional).diagnostics.some(item => item.code === 'missing-required-binding' && item.severity === 'warning')).toBe(true); });
});

describe('reference six-axis calibration remains topology-owned', () => {
  it('preserves zero-pose offsets, axes, directions, and bindings', () => { const joints = referenceServerSixAxisTopology.joints.filter(joint => joint.jointType !== 'fixed'); expect(joints.map(joint => joint.resolvedVisualJointId)).toEqual(['base', 'shoulder', 'elbow', 'wrist1', 'wrist2', 'wrist3']); expect(joints.map(joint => joint.axis)).toEqual([vector(0, 1, 0), vector(0, 0, 1), vector(0, 0, 1), vector(1, 0, 0), vector(0, 0, 1), vector(1, 0, 0)]); expect(resolveJointMotion(joints[1], 0).rotationRadians).toBe(-65 * Math.PI / 180); expect(resolveJointMotion(joints[2], 0).rotationRadians).toBe(75 * Math.PI / 180); });
  it('does not expose OPC UA source identity from the topology', () => { const text = JSON.stringify(referenceServerSixAxisTopology); expect(text).not.toContain('SAxis'); expect(text).not.toContain('MotionDevice'); expect(text).not.toContain('BrowseName'); });
});
