<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua" Version="2.0.0" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" Version="2.0.0" />
    <ProjectReference Include="..\Robotics.Client.Core\Robotics.Client.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
